"use client";

import { useEffect, useState, type FormEvent } from "react";
import AppShell from "@/components/AppShell";
import EmptyState from "@/components/EmptyState";
import { hubData, updateRecord, type StockItem } from "@/lib/hub-data";

export default function StockPage() {
  const [records, setRecords] = useState<StockItem[]>([]); const [show, setShow] = useState(false);
  const [form, setForm] = useState({ name: "", sku: "", quantity: 0, reorderLevel: 0, supplier: "" });
  useEffect(() => { const task = setTimeout(() => setRecords(hubData.stock()), 0); return () => clearTimeout(task); }, []);
  function submit(event: FormEvent) { event.preventDefault(); const updated = [{ id: crypto.randomUUID(), ...form }, ...records]; hubData.saveStock(updated); setRecords(updated); setShow(false); setForm({ name: "", sku: "", quantity: 0, reorderLevel: 0, supplier: "" }); }
  function quantity(id: string, value: number) { const updated = updateRecord(records, id, { quantity: Math.max(0, value) }); hubData.saveStock(updated); setRecords(updated); }
  return <AppShell title="Stock & materials" description="Track key material quantities and highlight items that need reordering." actions={<button className="primary-button" onClick={() => setShow(!show)}>{show ? "Close form" : "+ Add stock item"}</button>}>
    {show && <form onSubmit={submit} className="mb-6 grid gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-5"><Field label="Item name"><input required className="form-input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="SKU / code"><input className="form-input" value={form.sku} onChange={(e) => setForm({ ...form, sku: e.target.value })} /></Field><Field label="Quantity"><input required min="0" type="number" className="form-input" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: Number(e.target.value) })} /></Field><Field label="Reorder at"><input required min="0" type="number" className="form-input" value={form.reorderLevel} onChange={(e) => setForm({ ...form, reorderLevel: Number(e.target.value) })} /></Field><Field label="Supplier"><input className="form-input" value={form.supplier} onChange={(e) => setForm({ ...form, supplier: e.target.value })} /></Field><div className="sm:col-span-2 lg:col-span-5 lg:text-right"><button className="primary-button">Save stock item</button></div></form>}
    {!records.length ? <EmptyState title="No stock items yet" description="Add frequently used materials and set a reorder level for each one." /> : <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-[1fr_110px_130px] gap-3 border-b bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wide text-slate-500 md:grid-cols-[1fr_1fr_120px_140px] md:items-center"><span>Material</span><span className="hidden md:block">Supplier</span><span>In stock</span><span>Action</span></div>{records.map((item) => { const low = item.quantity <= item.reorderLevel; return <article key={item.id} className="grid grid-cols-[1fr_110px_130px] gap-3 border-b border-slate-100 px-5 py-4 last:border-0 md:grid-cols-[1fr_1fr_120px_140px] md:items-center"><div><strong className="text-slate-950">{item.name}</strong><small className="block text-slate-400">{item.sku || "No code"}</small></div><span className="hidden text-sm text-slate-600 md:block">{item.supplier || "Not set"}</span><div><strong className={low ? "text-rose-700" : "text-slate-900"}>{item.quantity}</strong>{low && <small className="block font-bold text-rose-600">Reorder</small>}</div><div className="flex gap-1"><button aria-label={`Remove one ${item.name}`} className="secondary-button" onClick={() => quantity(item.id, item.quantity - 1)}>−</button><button aria-label={`Add one ${item.name}`} className="secondary-button" onClick={() => quantity(item.id, item.quantity + 1)}>+</button></div></article>; })}</div>}
  </AppShell>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="field-label">{label}</span>{children}</label>; }
